version: '3.8'

services:
  convex-dev:
    build: .
    ports:
      - "3210:3210"  # Convex dev server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]

  expo-dev:
    build: .
    ports:
      - "8081:8081"  # Expo dev server
      - "19000:19000"  # Expo dev tools
      - "19001:19001"  # Expo dev tools
      - "19002:19002"  # Expo dev tools
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    command: ["npm", "start"]